; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 3
; RUN: llc -mtriple=gb -verify-machineinstrs -O3 < %s \
; RUN:   | FileCheck %s -check-prefix=GBI-O3

@addr = global ptr null

define i8 @test_addresses() nounwind {
; GBI-O3-LABEL: test_addresses:
; GBI-O3:       ; %bb.0:
; GBI-O3-NEXT:    ld de, .Ltmp0
; GBI-O3-NEXT:    ld bc, addr
; GBI-O3-NEXT:    ld h, b
; GBI-O3-NEXT:    ld l, c
; GBI-O3-NEXT:    ld (hl), e
; GBI-O3-NEXT:    ld a, c
; GBI-O3-NEXT:    add $01
; GBI-O3-NEXT:    ld l, a
; GBI-O3-NEXT:    ld a, b
; GBI-O3-NEXT:    adc $00
; GBI-O3-NEXT:    ld h, a
; GBI-O3-NEXT:    ld (hl), d
; GBI-O3-NEXT:    ld d, (hl)
; GBI-O3-NEXT:    ld h, b
; GBI-O3-NEXT:    ld l, c
; GBI-O3-NEXT:    ; kill: def $bc
; GBI-O3-NEXT:    ld e, (hl)
; GBI-O3-NEXT:    ld h, d
; GBI-O3-NEXT:    ld l, e
; GBI-O3-NEXT:    ; kill: def $de
; GBI-O3-NEXT:    jp (hl)
; GBI-O3-NEXT:  .Ltmp0: ; Block address taken
; GBI-O3-NEXT:  .LBB0_1: ; %block
; GBI-O3-NEXT:    ld a, $02
; GBI-O3-NEXT:    ret
  store volatile ptr blockaddress(@test_addresses, %block), ptr @addr
  %val = load volatile ptr, ptr @addr
  indirectbr ptr %val, [label %block]

block:
  ret i8 2
}


@val16 = local_unnamed_addr global i16 6546, align 8
define i16 @load_i16_global() nounwind {
; GBI-O3-LABEL: load_i16_global:
; GBI-O3:       ; %bb.0:
; GBI-O3-NEXT:    ld bc, val16
; GBI-O3-NEXT:    ld a, c
; GBI-O3-NEXT:    add $01
; GBI-O3-NEXT:    ld l, a
; GBI-O3-NEXT:    ld a, b
; GBI-O3-NEXT:    adc $00
; GBI-O3-NEXT:    ld h, a
; GBI-O3-NEXT:    ld d, (hl)
; GBI-O3-NEXT:    ld h, b
; GBI-O3-NEXT:    ld l, c
; GBI-O3-NEXT:    ; kill: def $bc
; GBI-O3-NEXT:    ld e, (hl)
; GBI-O3-NEXT:    ld h, d
; GBI-O3-NEXT:    ld l, e
; GBI-O3-NEXT:    ; kill: def $de
; GBI-O3-NEXT:    ret
  %1 = load i16, ptr @val16
  ret i16 %1
}


@G = global i16 0
define i16 @lw_sw_global(i16 %a) nounwind {
; GBI-O3-LABEL: lw_sw_global:
; GBI-O3:       ; %bb.0:
; GBI-O3-NEXT:    add sp, -4
; GBI-O3-NEXT:    ld b, h
; GBI-O3-NEXT:    ld a, l
; GBI-O3-NEXT:    ld hl, sp, 0
; GBI-O3-NEXT:    ldi (hl), a
; GBI-O3-NEXT:    ld (hl), b
; GBI-O3-NEXT:    ld de, G
; GBI-O3-NEXT:    ld h, d
; GBI-O3-NEXT:    ld l, e
; GBI-O3-NEXT:    ld c, (hl)
; GBI-O3-NEXT:    push hl
; GBI-O3-NEXT:    ld hl, sp, 4
; GBI-O3-NEXT:    ld (hl), c
; GBI-O3-NEXT:    inc hl
; GBI-O3-NEXT:    ld (hl), b
; GBI-O3-NEXT:    pop hl
; GBI-O3-NEXT:    push hl
; GBI-O3-NEXT:    ld hl, sp, 2
; GBI-O3-NEXT:    ld c, (hl)
; GBI-O3-NEXT:    inc hl
; GBI-O3-NEXT:    ld b, (hl)
; GBI-O3-NEXT:    pop hl
; GBI-O3-NEXT:    ld (hl), c
; GBI-O3-NEXT:    ld a, e
; GBI-O3-NEXT:    add $01
; GBI-O3-NEXT:    ld l, a
; GBI-O3-NEXT:    ld a, d
; GBI-O3-NEXT:    adc $00
; GBI-O3-NEXT:    ld h, a
; GBI-O3-NEXT:    push hl
; GBI-O3-NEXT:    ld hl, sp, 4
; GBI-O3-NEXT:    ld c, (hl)
; GBI-O3-NEXT:    inc hl
; GBI-O3-NEXT:    ld b, (hl)
; GBI-O3-NEXT:    pop hl
; GBI-O3-NEXT:    ld b, (hl)
; GBI-O3-NEXT:    push hl
; GBI-O3-NEXT:    ld hl, sp, 4
; GBI-O3-NEXT:    ld (hl), c
; GBI-O3-NEXT:    inc hl
; GBI-O3-NEXT:    ld (hl), b
; GBI-O3-NEXT:    pop hl
; GBI-O3-NEXT:    push hl
; GBI-O3-NEXT:    ld hl, sp, 2
; GBI-O3-NEXT:    ld c, (hl)
; GBI-O3-NEXT:    inc hl
; GBI-O3-NEXT:    ld b, (hl)
; GBI-O3-NEXT:    pop hl
; GBI-O3-NEXT:    ld (hl), b
; GBI-O3-NEXT:    ld a, e
; GBI-O3-NEXT:    add $12
; GBI-O3-NEXT:    ld l, a
; GBI-O3-NEXT:    ld a, d
; GBI-O3-NEXT:    adc $00
; GBI-O3-NEXT:    ld h, a
; GBI-O3-NEXT:    ld a, (hl)
; GBI-O3-NEXT:    ld (hl), c
; GBI-O3-NEXT:    ld a, l
; GBI-O3-NEXT:    add $01
; GBI-O3-NEXT:    ld e, a
; GBI-O3-NEXT:    ld a, h
; GBI-O3-NEXT:    adc $00
; GBI-O3-NEXT:    ld d, a
; GBI-O3-NEXT:    ld h, d
; GBI-O3-NEXT:    ld l, e
; GBI-O3-NEXT:    ld a, (hl)
; GBI-O3-NEXT:    ld (hl), b
; GBI-O3-NEXT:    ld hl, sp, 2
; GBI-O3-NEXT:    ldi a, (hl)
; GBI-O3-NEXT:    ld h, (hl)
; GBI-O3-NEXT:    ld l, a
; GBI-O3-NEXT:    add sp, 4
; GBI-O3-NEXT:    ret
  %1 = load volatile i16, ptr @G
  store i16 %a, ptr @G
  %2 = getelementptr i16, ptr @G, i16 9
  %3 = load volatile i16, ptr %2
  store i16 %a, ptr %2
  ret i16 %1
}
