; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 3
; RUN: llc -mtriple=gb -verify-machineinstrs -O3 < %s \
; RUN:   | FileCheck %s -check-prefix=GBI-O3

@addr = global ptr null

define i8 @test_addresses() nounwind {
; GBI-O3-LABEL: test_addresses:
; GBI-O3:       # %bb.0:
; GBI-O3-NEXT:    ld a, %lo .Ltmp0
; GBI-O3-NEXT:    ld (addr), a
; GBI-O3-NEXT:    ld a, %hi .Ltmp0
; GBI-O3-NEXT:    ld (addr+1), a
; GBI-O3-NEXT:    ld a, (addr)
; GBI-O3-NEXT:    ld l, a
; GBI-O3-NEXT:    ld a, (addr+1)
; GBI-O3-NEXT:    ld h, a
; GBI-O3-NEXT:    jp (hl)
; GBI-O3-NEXT:  .Ltmp0: # Block address taken
; GBI-O3-NEXT:  .LBB0_1: # %block
; GBI-O3-NEXT:    ld a, $02
; GBI-O3-NEXT:    ret
  store volatile ptr blockaddress(@test_addresses, %block), ptr @addr
  %val = load volatile ptr, ptr @addr
  indirectbr ptr %val, [label %block]

block:
  ret i8 2
}


@val16 = local_unnamed_addr global i16 6546, align 8
define i16 @load_i16_global() nounwind {
; GBI-O3-LABEL: load_i16_global:
; GBI-O3:       # %bb.0:
; GBI-O3-NEXT:    ld a, (val16)
; GBI-O3-NEXT:    ld l, a
; GBI-O3-NEXT:    ld a, (val16+1)
; GBI-O3-NEXT:    ld h, a
; GBI-O3-NEXT:    ret
  %1 = load i16, ptr @val16
  ret i16 %1
}


@G = global i16 0
define fastcc i16 @lw_sw_global(i16 %a) nounwind {
; GBI-O3-LABEL: lw_sw_global:
; GBI-O3:       # %bb.0:
; GBI-O3-NEXT:    ld a, (G)
; GBI-O3-NEXT:    ld c, a
; GBI-O3-NEXT:    ld a, (G+1)
; GBI-O3-NEXT:    ld b, a
; GBI-O3-NEXT:    ld a, l
; GBI-O3-NEXT:    ld (G), a
; GBI-O3-NEXT:    ld a, h
; GBI-O3-NEXT:    ld (G+1), a
; GBI-O3-NEXT:    ld a, (G+18)
; GBI-O3-NEXT:    ld a, (G+19)
; GBI-O3-NEXT:    ld a, l
; GBI-O3-NEXT:    ld (G+18), a
; GBI-O3-NEXT:    ld a, h
; GBI-O3-NEXT:    ld (G+19), a
; GBI-O3-NEXT:    ld h, b
; GBI-O3-NEXT:    ld l, c
; GBI-O3-NEXT:    ret
  %1 = load volatile i16, ptr @G
  store i16 %a, ptr @G
  %2 = getelementptr i16, ptr @G, i16 9
  %3 = load volatile i16, ptr %2
  store i16 %a, ptr %2
  ret i16 %1
}

@external_u16 = external dso_local global ptr, align 2

define dso_local noundef i16 @test_save_i16_to_external() local_unnamed_addr {
; GBI-O3-LABEL: test_save_i16_to_external:
; GBI-O3:       # %bb.0: # %entry
; GBI-O3-NEXT:    ld hl, $0000
; GBI-O3-NEXT:    ld a, $12
; GBI-O3-NEXT:    ld (external_u16), a
; GBI-O3-NEXT:    ld a, $11
; GBI-O3-NEXT:    ld (external_u16+1), a
; GBI-O3-NEXT:    ret
entry:
  store ptr inttoptr (i16 4370 to ptr), ptr @external_u16, align 2
  ret i16 0
}
