; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 3
; RUN: llc -mtriple=gb -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=GBI

define i8 @add(i8 %b, i8 %c) nounwind {
; GBI-LABEL: add:
; GBI:       ; %bb.0:
; GBI-NEXT:    ld a, b
; GBI-NEXT:    add c
; GBI-NEXT:    ret
  %1 = add i8 %b, %c
  ret i8 %1
}

define i8 @addi(i8 %b) nounwind {
; GBI-LABEL: addi:
; GBI:       ; %bb.0:
; GBI-NEXT:    ld a, b
; GBI-NEXT:    add 1
; GBI-NEXT:    ret
  %1 = add i8 %b, 1
  ret i8 %1
}

define i8 @sub(i8 %b, i8 %c) nounwind {
; GBI-LABEL: sub:
; GBI:       ; %bb.0:
; GBI-NEXT:    ld a, b
; GBI-NEXT:    sub c
; GBI-NEXT:    ret
  %1 = sub i8 %b, %c
  ret i8 %1
}

define i8 @subi(i8 %b) nounwind {
; GBI-LABEL: subi:
; GBI:       ; %bb.0:
; GBI-NEXT:    ld a, b
; GBI-NEXT:    add -1
; GBI-NEXT:    ret
  %1 = sub i8 %b, 1
  ret i8 %1
}

define i8 @and(i8 %b, i8 %c) nounwind {
; GBI-LABEL: and:
; GBI:       ; %bb.0:
; GBI-NEXT:    ld a, b
; GBI-NEXT:    and c
; GBI-NEXT:    ret
  %1 = and i8 %b, %c
  ret i8 %1
}

define i8 @andi(i8 %b) nounwind {
; GBI-LABEL: andi:
; GBI:       ; %bb.0:
; GBI-NEXT:    ld a, b
; GBI-NEXT:    and 1
; GBI-NEXT:    ret
  %1 = and i8 %b, 1
  ret i8 %1
}

define i8 @xor(i8 %b, i8 %c) nounwind {
; GBI-LABEL: xor:
; GBI:       ; %bb.0:
; GBI-NEXT:    ld a, b
; GBI-NEXT:    xor c
; GBI-NEXT:    ret
  %1 = xor i8 %b, %c
  ret i8 %1
}

define i8 @xori(i8 %b) nounwind {
; GBI-LABEL: xori:
; GBI:       ; %bb.0:
; GBI-NEXT:    ld a, b
; GBI-NEXT:    xor 1
; GBI-NEXT:    ret
  %1 = xor i8 %b, 1
  ret i8 %1
}

define i8 @or(i8 %b, i8 %c) nounwind {
; GBI-LABEL: or:
; GBI:       ; %bb.0:
; GBI-NEXT:    ld a, b
; GBI-NEXT:    or c
; GBI-NEXT:    ret
  %1 = or i8 %b, %c
  ret i8 %1
}

define i8 @ori(i8 %b) nounwind {
; GBI-LABEL: ori:
; GBI:       ; %bb.0:
; GBI-NEXT:    ld a, b
; GBI-NEXT:    or 1
; GBI-NEXT:    ret
  %1 = or i8 %b, 1
  ret i8 %1
}

define i8 @constant8() nounwind {
; GBI-LABEL: constant8:
; GBI:       ; %bb.0:
; GBI-NEXT:    ld a, $ff
; GBI-NEXT:    ret
  ret i8 -1
}

define i16 @constantS16() nounwind {
; GBI-LABEL: constantS16:
; GBI:       ; %bb.0:
; GBI-NEXT:    ld hl, $ffff
; GBI-NEXT:    ret
  ret i16 -1
}

define i16 @constantU16() nounwind {
; GBI-LABEL: constantU16:
; GBI:       ; %bb.0:
; GBI-NEXT:    ld hl, $09a0
; GBI-NEXT:    ret
  ret i16 2464
}

define i16 @constantAmbiguousU16() nounwind {
; GBI-LABEL: constantAmbiguousU16:
; GBI:       ; %bb.0:
; GBI-NEXT:    ld hl, $0001
; GBI-NEXT:    ret
  ret i16 1
}

define i16 @add16(i16 %a) nounwind {
; GBI-LABEL: add16:
; GBI:       ; %bb.0:
; GBI-NEXT:    ld bc, $0014
; GBI-NEXT:    add hl, bc
; GBI-NEXT:    ret
  %1 = add i16 %a, 20
  ret i16 %1
}
