; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 3
; RUN: llc -mtriple=gb -verify-machineinstrs -O3 < %s \
; RUN:   | FileCheck %s -check-prefix=GBI-O3

define i8 @simple_branch(i8 %b, i8 %c) nounwind {
; GBI-O3-LABEL: simple_branch:
; GBI-O3:       # %bb.0:
; GBI-O3-NEXT:    ld a, $00
; GBI-O3-NEXT:    ret
  br label %label1
label1:
  ret i8 0
}

define i8 @sge(i8 %b, i8 %c) nounwind {
; GBI-O3-LABEL: sge:
; GBI-O3:       # %bb.0:
; GBI-O3-NEXT:    ld a, b
; GBI-O3-NEXT:    xor c
; GBI-O3-NEXT:    bit 7, a
; GBI-O3-NEXT:    jr nz, .LBB1_3
; GBI-O3-NEXT:  # %bb.1:
; GBI-O3-NEXT:    xor c
; GBI-O3-NEXT:    cp c
; GBI-O3-NEXT:    jr nc, .LBB1_4
; GBI-O3-NEXT:  .LBB1_2: # %label2
; GBI-O3-NEXT:    ld a, $00
; GBI-O3-NEXT:    ret
; GBI-O3-NEXT:  .LBB1_3:
; GBI-O3-NEXT:    bit 7, c
; GBI-O3-NEXT:    jr z, .LBB1_2
; GBI-O3-NEXT:  .LBB1_4: # %label1
; GBI-O3-NEXT:    ld a, $01
; GBI-O3-NEXT:    ret
  %result = icmp sge i8 %b, %c
  br i1 %result, label %label1, label %label2
label1:
  ret i8 1
label2:
  ret i8 0
}

define i8 @sgt(i8 %b, i8 %c) nounwind {
; GBI-O3-LABEL: sgt:
; GBI-O3:       # %bb.0:
; GBI-O3-NEXT:    ld a, b
; GBI-O3-NEXT:    xor c
; GBI-O3-NEXT:    bit 7, a
; GBI-O3-NEXT:    jr nz, .LBB2_3
; GBI-O3-NEXT:  # %bb.1:
; GBI-O3-NEXT:    xor b
; GBI-O3-NEXT:    cp b
; GBI-O3-NEXT:    jr c, .LBB2_4
; GBI-O3-NEXT:  .LBB2_2: # %label2
; GBI-O3-NEXT:    ld a, $00
; GBI-O3-NEXT:    ret
; GBI-O3-NEXT:  .LBB2_3:
; GBI-O3-NEXT:    bit 7, b
; GBI-O3-NEXT:    jr nz, .LBB2_2
; GBI-O3-NEXT:  .LBB2_4: # %label1
; GBI-O3-NEXT:    ld a, $01
; GBI-O3-NEXT:    ret
  %result = icmp sgt i8 %b, %c
  br i1 %result, label %label1, label %label2
label1:
  ret i8 1
label2:
  ret i8 0
}

define i8 @sgt_0(i8 %b) nounwind {
; GBI-O3-LABEL: sgt_0:
; GBI-O3:       # %bb.0:
; GBI-O3-NEXT:    bit 7, b
; GBI-O3-NEXT:    jr nz, .LBB3_3
; GBI-O3-NEXT:  # %bb.1:
; GBI-O3-NEXT:    inc b
; GBI-O3-NEXT:    dec b
; GBI-O3-NEXT:    jr z, .LBB3_3
; GBI-O3-NEXT:  # %bb.2: # %label1
; GBI-O3-NEXT:    ld a, $01
; GBI-O3-NEXT:    ret
; GBI-O3-NEXT:  .LBB3_3: # %label2
; GBI-O3-NEXT:    ld a, $00
; GBI-O3-NEXT:    ret
  %result = icmp sgt i8 %b, 0
  br i1 %result, label %label1, label %label2
label1:
  ret i8 1
label2:
  ret i8 0
}

define i8 @sle_0(i8 %b) nounwind {
; GBI-O3-LABEL: sle_0:
; GBI-O3:       # %bb.0:
; GBI-O3-NEXT:    bit 7, b
; GBI-O3-NEXT:    jr nz, .LBB4_2
; GBI-O3-NEXT:  # %bb.1:
; GBI-O3-NEXT:    inc b
; GBI-O3-NEXT:    dec b
; GBI-O3-NEXT:    jr nz, .LBB4_3
; GBI-O3-NEXT:  .LBB4_2: # %label1
; GBI-O3-NEXT:    ld a, $01
; GBI-O3-NEXT:    ret
; GBI-O3-NEXT:  .LBB4_3: # %label2
; GBI-O3-NEXT:    ld a, $00
; GBI-O3-NEXT:    ret
  %result = icmp sle i8 %b, 0
  br i1 %result, label %label1, label %label2
label1:
  ret i8 1
label2:
  ret i8 0
}

define i8 @sgt_1(i8 %b) nounwind {
; GBI-O3-LABEL: sgt_1:
; GBI-O3:       # %bb.0:
; GBI-O3-NEXT:    bit 7, b
; GBI-O3-NEXT:    jr nz, .LBB5_3
; GBI-O3-NEXT:  # %bb.1:
; GBI-O3-NEXT:    ld a, b
; GBI-O3-NEXT:    cp $02
; GBI-O3-NEXT:    jr c, .LBB5_3
; GBI-O3-NEXT:  # %bb.2: # %label1
; GBI-O3-NEXT:    ld a, $01
; GBI-O3-NEXT:    ret
; GBI-O3-NEXT:  .LBB5_3: # %label2
; GBI-O3-NEXT:    ld a, $00
; GBI-O3-NEXT:    ret
  %result = icmp sgt i8 %b, 1
  br i1 %result, label %label1, label %label2
label1:
  ret i8 1
label2:
  ret i8 0
}

define i8 @sgt_n1(i8 %b) nounwind {
; GBI-O3-LABEL: sgt_n1:
; GBI-O3:       # %bb.0:
; GBI-O3-NEXT:    ld a, b
; GBI-O3-NEXT:    cp $80
; GBI-O3-NEXT:    jr nc, .LBB6_2
; GBI-O3-NEXT:  # %bb.1: # %label1
; GBI-O3-NEXT:    ld a, $01
; GBI-O3-NEXT:    ret
; GBI-O3-NEXT:  .LBB6_2: # %label2
; GBI-O3-NEXT:    ld a, $00
; GBI-O3-NEXT:    ret
  %result = icmp sgt i8 %b, -1
  br i1 %result, label %label1, label %label2
label1:
  ret i8 1
label2:
  ret i8 0
}

define i8 @sgt_n127(i8 %b) nounwind {
; GBI-O3-LABEL: sgt_n127:
; GBI-O3:       # %bb.0:
; GBI-O3-NEXT:    bit 7, b
; GBI-O3-NEXT:    jr z, .LBB7_2
; GBI-O3-NEXT:  # %bb.1:
; GBI-O3-NEXT:    ld a, b
; GBI-O3-NEXT:    cp $82
; GBI-O3-NEXT:    jr c, .LBB7_3
; GBI-O3-NEXT:  .LBB7_2: # %label1
; GBI-O3-NEXT:    ld a, $01
; GBI-O3-NEXT:    ret
; GBI-O3-NEXT:  .LBB7_3: # %label2
; GBI-O3-NEXT:    ld a, $00
; GBI-O3-NEXT:    ret
  %result = icmp sgt i8 %b, -127
  br i1 %result, label %label1, label %label2
label1:
  ret i8 1
label2:
  ret i8 0
}


define i8 @sle(i8 %b, i8 %c) nounwind {
; GBI-O3-LABEL: sle:
; GBI-O3:       # %bb.0:
; GBI-O3-NEXT:    ld a, b
; GBI-O3-NEXT:    xor c
; GBI-O3-NEXT:    bit 7, a
; GBI-O3-NEXT:    jr nz, .LBB8_3
; GBI-O3-NEXT:  # %bb.1:
; GBI-O3-NEXT:    xor b
; GBI-O3-NEXT:    cp b
; GBI-O3-NEXT:    jr nc, .LBB8_4
; GBI-O3-NEXT:  .LBB8_2: # %label2
; GBI-O3-NEXT:    ld a, $00
; GBI-O3-NEXT:    ret
; GBI-O3-NEXT:  .LBB8_3:
; GBI-O3-NEXT:    bit 7, b
; GBI-O3-NEXT:    jr z, .LBB8_2
; GBI-O3-NEXT:  .LBB8_4: # %label1
; GBI-O3-NEXT:    ld a, $01
; GBI-O3-NEXT:    ret
  %result = icmp sle i8 %b, %c
  br i1 %result, label %label1, label %label2
label1:
  ret i8 1
label2:
  ret i8 0
}

define i8 @slt(i8 %b, i8 %c) nounwind {
; GBI-O3-LABEL: slt:
; GBI-O3:       # %bb.0:
; GBI-O3-NEXT:    ld a, b
; GBI-O3-NEXT:    xor c
; GBI-O3-NEXT:    bit 7, a
; GBI-O3-NEXT:    jr nz, .LBB9_3
; GBI-O3-NEXT:  # %bb.1:
; GBI-O3-NEXT:    xor c
; GBI-O3-NEXT:    cp c
; GBI-O3-NEXT:    jr c, .LBB9_4
; GBI-O3-NEXT:  .LBB9_2: # %label2
; GBI-O3-NEXT:    ld a, $00
; GBI-O3-NEXT:    ret
; GBI-O3-NEXT:  .LBB9_3:
; GBI-O3-NEXT:    bit 7, c
; GBI-O3-NEXT:    jr nz, .LBB9_2
; GBI-O3-NEXT:  .LBB9_4: # %label1
; GBI-O3-NEXT:    ld a, $01
; GBI-O3-NEXT:    ret
  %result = icmp slt i8 %b, %c
  br i1 %result, label %label1, label %label2
label1:
  ret i8 1
label2:
  ret i8 0
}

define i8 @uge(i8 %b, i8 %c) nounwind {
; GBI-O3-LABEL: uge:
; GBI-O3:       # %bb.0:
; GBI-O3-NEXT:    ld a, b
; GBI-O3-NEXT:    cp c
; GBI-O3-NEXT:    jr c, .LBB10_2
; GBI-O3-NEXT:  # %bb.1: # %label1
; GBI-O3-NEXT:    ld a, $01
; GBI-O3-NEXT:    ret
; GBI-O3-NEXT:  .LBB10_2: # %label2
; GBI-O3-NEXT:    ld a, $00
; GBI-O3-NEXT:    ret
  %result = icmp uge i8 %b, %c
  br i1 %result, label %label1, label %label2
label1:
  ret i8 1
label2:
  ret i8 0
}

define i8 @ugt(i8 %b, i8 %c) nounwind {
; GBI-O3-LABEL: ugt:
; GBI-O3:       # %bb.0:
; GBI-O3-NEXT:    ld a, c
; GBI-O3-NEXT:    cp b
; GBI-O3-NEXT:    jr nc, .LBB11_2
; GBI-O3-NEXT:  # %bb.1: # %label1
; GBI-O3-NEXT:    ld a, $01
; GBI-O3-NEXT:    ret
; GBI-O3-NEXT:  .LBB11_2: # %label2
; GBI-O3-NEXT:    ld a, $00
; GBI-O3-NEXT:    ret
  %result = icmp ugt i8 %b, %c
  br i1 %result, label %label1, label %label2
label1:
  ret i8 1
label2:
  ret i8 0
}

define i8 @ule(i8 %b, i8 %c) nounwind {
; GBI-O3-LABEL: ule:
; GBI-O3:       # %bb.0:
; GBI-O3-NEXT:    ld a, c
; GBI-O3-NEXT:    cp b
; GBI-O3-NEXT:    jr c, .LBB12_2
; GBI-O3-NEXT:  # %bb.1: # %label1
; GBI-O3-NEXT:    ld a, $01
; GBI-O3-NEXT:    ret
; GBI-O3-NEXT:  .LBB12_2: # %label2
; GBI-O3-NEXT:    ld a, $00
; GBI-O3-NEXT:    ret
  %result = icmp ule i8 %b, %c
  br i1 %result, label %label1, label %label2
label1:
  ret i8 1
label2:
  ret i8 0
}

define i8 @ult(i8 %b, i8 %c) nounwind {
; GBI-O3-LABEL: ult:
; GBI-O3:       # %bb.0:
; GBI-O3-NEXT:    ld a, b
; GBI-O3-NEXT:    cp c
; GBI-O3-NEXT:    jr nc, .LBB13_2
; GBI-O3-NEXT:  # %bb.1: # %label1
; GBI-O3-NEXT:    ld a, $01
; GBI-O3-NEXT:    ret
; GBI-O3-NEXT:  .LBB13_2: # %label2
; GBI-O3-NEXT:    ld a, $00
; GBI-O3-NEXT:    ret
  %result = icmp ult i8 %b, %c
  br i1 %result, label %label1, label %label2
label1:
  ret i8 1
label2:
  ret i8 0
}


define i8 @eq(i8 %b, i8 %c) nounwind {
; GBI-O3-LABEL: eq:
; GBI-O3:       # %bb.0:
; GBI-O3-NEXT:    ld a, b
; GBI-O3-NEXT:    cp c
; GBI-O3-NEXT:    jr nz, .LBB14_2
; GBI-O3-NEXT:  # %bb.1: # %label1
; GBI-O3-NEXT:    ld a, $01
; GBI-O3-NEXT:    ret
; GBI-O3-NEXT:  .LBB14_2: # %label2
; GBI-O3-NEXT:    ld a, $00
; GBI-O3-NEXT:    ret
  %result = icmp eq i8 %b, %c
  br i1 %result, label %label1, label %label2
label1:
  ret i8 1
label2:
  ret i8 0
}

define i8 @ne(i8 %b, i8 %c) nounwind {
; GBI-O3-LABEL: ne:
; GBI-O3:       # %bb.0:
; GBI-O3-NEXT:    ld a, b
; GBI-O3-NEXT:    cp c
; GBI-O3-NEXT:    jr z, .LBB15_2
; GBI-O3-NEXT:  # %bb.1: # %label1
; GBI-O3-NEXT:    ld a, $01
; GBI-O3-NEXT:    ret
; GBI-O3-NEXT:  .LBB15_2: # %label2
; GBI-O3-NEXT:    ld a, $00
; GBI-O3-NEXT:    ret
  %result = icmp ne i8 %b, %c
  br i1 %result, label %label1, label %label2
label1:
  ret i8 1
label2:
  ret i8 0
}

define i8 @phi(i1 %b) nounwind {
; GBI-O3-LABEL: phi:
; GBI-O3:       # %bb.0:
; GBI-O3-NEXT:    bit 0, b
; GBI-O3-NEXT:    jr z, .LBB16_2
; GBI-O3-NEXT:  # %bb.1:
; GBI-O3-NEXT:    ld a, $04
; GBI-O3-NEXT:    ret
; GBI-O3-NEXT:  .LBB16_2: # %label2
; GBI-O3-NEXT:    ld a, $05
; GBI-O3-NEXT:    ret
  br i1 %b, label %label1, label %label2
label1:
  br label %end
label2:
  br label %end
end:
  %result = phi i8 [4, %label1], [5, %label2]
  ret i8 %result
}

define i8 @select(i1 %b) nounwind {
; GBI-O3-LABEL: select:
; GBI-O3:       # %bb.0:
; GBI-O3-NEXT:    bit 0, b
; GBI-O3-NEXT:    jr z, .LBB17_2
; GBI-O3-NEXT:  # %bb.1:
; GBI-O3-NEXT:    ld a, $04
; GBI-O3-NEXT:    ret
; GBI-O3-NEXT:  .LBB17_2: # %select.false
; GBI-O3-NEXT:    ld a, $05
; GBI-O3-NEXT:    ret
  %result = select i1 %b, i8 4, i8 5
  ret i8 %result
}

define fastcc void @jt(i8 %in, ptr %out) {
; GBI-O3-LABEL: jt:
; GBI-O3:       # %bb.0: # %entry
; GBI-O3-NEXT:    ld a, b
; GBI-O3-NEXT:    bit 7, b
; GBI-O3-NEXT:    jr nz, .LBB18_2
; GBI-O3-NEXT:  # %bb.1: # %entry
; GBI-O3-NEXT:    cp $03
; GBI-O3-NEXT:    jr nc, .LBB18_6
; GBI-O3-NEXT:  .LBB18_2: # %entry
; GBI-O3-NEXT:    cp $01
; GBI-O3-NEXT:    jr z, .LBB18_5
; GBI-O3-NEXT:  # %bb.3: # %entry
; GBI-O3-NEXT:    cp $02
; GBI-O3-NEXT:    jr nz, .LBB18_11
; GBI-O3-NEXT:  # %bb.4: # %bb2
; GBI-O3-NEXT:    ld a, $03
; GBI-O3-NEXT:    jr .LBB18_10
; GBI-O3-NEXT:  .LBB18_5: # %bb1
; GBI-O3-NEXT:    ld a, $04
; GBI-O3-NEXT:    jr .LBB18_10
; GBI-O3-NEXT:  .LBB18_6: # %entry
; GBI-O3-NEXT:    cp $03
; GBI-O3-NEXT:    jr z, .LBB18_9
; GBI-O3-NEXT:  # %bb.7: # %entry
; GBI-O3-NEXT:    cp $04
; GBI-O3-NEXT:    jr nz, .LBB18_11
; GBI-O3-NEXT:  # %bb.8: # %bb4
; GBI-O3-NEXT:    ld a, $01
; GBI-O3-NEXT:    jr .LBB18_10
; GBI-O3-NEXT:  .LBB18_9: # %bb3
; GBI-O3-NEXT:    ld a, $02
; GBI-O3-NEXT:  .LBB18_10: # %exit
; GBI-O3-NEXT:    ld (hl), a
; GBI-O3-NEXT:  .LBB18_11: # %exit
; GBI-O3-NEXT:    ret
entry:
  switch i8 %in, label %exit [
    i8 1, label %bb1
    i8 2, label %bb2
    i8 3, label %bb3
    i8 4, label %bb4
  ]
bb1:
  store i8 4, ptr %out
  br label %exit
bb2:
  store i8 3, ptr %out
  br label %exit
bb3:
  store i8 2, ptr %out
  br label %exit
bb4:
  store i8 1, ptr %out
  br label %exit
exit:
  ret void
}

define fastcc i8 @indirectbr(ptr %target) nounwind {
; GBI-O3-LABEL: indirectbr:
; GBI-O3:       # %bb.0:
; GBI-O3-NEXT:    jp (hl)
; GBI-O3-NEXT:  .LBB19_1: # %test_label1
; GBI-O3-NEXT:    ld a, $01
; GBI-O3-NEXT:    ret
; GBI-O3-NEXT:  .LBB19_2: # %test_label2
; GBI-O3-NEXT:    ld a, $00
; GBI-O3-NEXT:    ret
  indirectbr ptr %target, [label %test_label1, label %test_label2]
test_label1:
  ret i8 1
test_label2:
  br label %ret
ret:
  ret i8 0
}

declare void @some_fn();
declare void @some_other_fn();

define void @pred_ret(i8 %b) nounwind {
; GBI-O3-LABEL: pred_ret:
; GBI-O3:       # %bb.0:
; GBI-O3-NEXT:    inc b
; GBI-O3-NEXT:    dec b
; GBI-O3-NEXT:    ret nz
; GBI-O3-NEXT:    call some_fn
; GBI-O3-NEXT:    ret
  %result = icmp ugt i8 %b, 0
  br i1 %result, label %true, label %false
true:
  ret void
false:
  call void @some_fn()
  ret void
}

define void @pred_call(i8 %b) nounwind {
; GBI-O3-LABEL: pred_call:
; GBI-O3:       # %bb.0:
; GBI-O3-NEXT:    inc b
; GBI-O3-NEXT:    dec b
; GBI-O3-NEXT:    call nz, some_other_fn
; GBI-O3-NEXT:    call some_fn
; GBI-O3-NEXT:    call some_fn
; GBI-O3-NEXT:    ret
  %result = icmp ugt i8 %b, 0
  br i1 %result, label %true, label %false
true:
  call void @some_other_fn()
  br label %false
false:
  call void @some_fn()
  call void @some_fn()
  ret void
}

define void @no_pred_call_ret(i8 %b) nounwind {
; GBI-O3-LABEL: no_pred_call_ret:
; GBI-O3:       # %bb.0:
; GBI-O3-NEXT:    inc b
; GBI-O3-NEXT:    dec b
; GBI-O3-NEXT:    jr z, .LBB22_2
; GBI-O3-NEXT:  # %bb.1: # %true
; GBI-O3-NEXT:    call some_fn
; GBI-O3-NEXT:    ret
; GBI-O3-NEXT:  .LBB22_2: # %false
; GBI-O3-NEXT:    call some_other_fn
; GBI-O3-NEXT:    ret
  %result = icmp ugt i8 %b, 0
  br i1 %result, label %true, label %false
true:
  call void @some_fn()
  ret void
false:
  call void @some_other_fn()
  ret void
}

define dso_local void @loop(i8 %amount) {
; GBI-O3-LABEL: loop:
; GBI-O3:       # %bb.0: # %entry
; GBI-O3-NEXT:    add sp, -2
; GBI-O3-NEXT:    inc b
; GBI-O3-NEXT:    dec b
; GBI-O3-NEXT:    jr z, .LBB23_2
; GBI-O3-NEXT:  .LBB23_1: # %for.body
; GBI-O3-NEXT:    # =>This Inner Loop Header: Depth=1
; GBI-O3-NEXT:    ld hl, sp, 1
; GBI-O3-NEXT:    ld (hl), b
; GBI-O3-NEXT:    call some_fn
; GBI-O3-NEXT:    ld hl, sp, 1
; GBI-O3-NEXT:    ld b, (hl)
; GBI-O3-NEXT:    dec b
; GBI-O3-NEXT:    jr nz, .LBB23_1
; GBI-O3-NEXT:  .LBB23_2: # %for.cond.cleanup
; GBI-O3-NEXT:    add sp, 2
; GBI-O3-NEXT:    ret
entry:
  %cmp5.not = icmp eq i8 %amount, 0
  br i1 %cmp5.not, label %for.cond.cleanup, label %for.body

for.cond.cleanup:
  ret void

for.body:
  %i.06 = phi i8 [ %add, %for.body ], [ 0, %entry ]
  tail call void @some_fn()
  %add = add nuw i8 %i.06, 1
  %exitcond.not = icmp eq i8 %add, %amount
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}
