; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=gb -verify-machineinstrs -O3 < %s \
; RUN:   | FileCheck %s -check-prefix=GBI-O3


define i32 @as_u32(i32 %0) {
; GBI-O3-LABEL: as_u32:
; GBI-O3:       # %bb.0: # %begin
; GBI-O3-NEXT:    ld a, $00
; GBI-O3-NEXT:    ld (bc), a
; GBI-O3-NEXT:    inc bc
; GBI-O3-NEXT:    ld (bc), a
; GBI-O3-NEXT:    inc bc
; GBI-O3-NEXT:    ld (bc), a
; GBI-O3-NEXT:    inc bc
; GBI-O3-NEXT:    ld (bc), a
; GBI-O3-NEXT:    ret
begin:
    #dbg_value(i32 %0, !3, !DIExpression(), !DILocation(line: 0, scope: !4))
  ret i32 0
}

!0 = distinct !DICompileUnit(language: DW_LANG_C_plus_plus, file: !1, producer: "glang", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug, splitDebugInlining: false, nameTableKind: None)
!1 = !DIFile(filename: "file", directory: "/")
!2 = !{i32 1, !"Debug Info Version", i32 3}
!3 = !DILocalVariable(name: "value", scope: !4, file: !5, line: 76, type: !8)
!4 = distinct !DISubprogram(name: "as_u128", linkageName: "as_u32", scope: !5, file: !5, line: 76, type: !6, scopeLine: 76, spFlags: DISPFlagDefinition, unit: !0)
!5 = !DIFile(filename: "util.c3", directory: "/")
!6 = !DISubroutineType(types: !7)
!7 = !{null, null}
!8 = !DIBasicType(name: "u128", size: 128, encoding: DW_ATE_unsigned)
!9 = !DILocation(line: 0, scope: !4)
