; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 3
; RUN: llc -mtriple=gb -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=GBI

define i8 @load8(ptr %a) nounwind {
; GBI-LABEL: load8:
; GBI:       ; %bb.0:
; GBI-NEXT:    ld a, (hl)
; GBI-NEXT:    ret
  %1 = load i8, ptr %a
  ret i8 %1
}

define void @store8(ptr %a, i8 %b) nounwind {
; GBI-LABEL: store8:
; GBI:       ; %bb.0:
; GBI-NEXT:    ld (hl), b
; GBI-NEXT:    ret
  store i8 %b, ptr %a
  ret void
}
