; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 3
; RUN: llc -mtriple=gb -verify-machineinstrs -O3 < %s \
; RUN:   | FileCheck %s -check-prefix=GBI-O3

define fastcc i8 @trunc_i32(i32 %0) {
; GBI-O3-LABEL: trunc_i32:
; GBI-O3:       # %bb.0:
; GBI-O3-NEXT:    ld a, l
; GBI-O3-NEXT:    ret
  %res = trunc i32 %0 to i8
  ret i8 %res
}

define fastcc i8 @trunc_i16(i16 %0) {
; GBI-O3-LABEL: trunc_i16:
; GBI-O3:       # %bb.0:
; GBI-O3-NEXT:    ld a, l
; GBI-O3-NEXT:    ret
  %res = trunc i16 %0 to i8
  ret i8 %res
}

define fastcc i1 @trunc_i1(i8 %0) {
; GBI-O3-LABEL: trunc_i1:
; GBI-O3:       # %bb.0:
; GBI-O3-NEXT:    ld a, b
; GBI-O3-NEXT:    ret
  %res = trunc i8 %0 to i1
  ret i1 %res
}

define fastcc i8 @sext8_i1(i1 %0) {
; GBI-O3-LABEL: sext8_i1:
; GBI-O3:       # %bb.0:
; GBI-O3-NEXT:    ld a, b
; GBI-O3-NEXT:    and $01
; GBI-O3-NEXT:    dec a
; GBI-O3-NEXT:    cpl
; GBI-O3-NEXT:    ret
  %res = sext i1 %0 to i8
  ret i8 %res
}

define fastcc i16 @sext16_i1(i1 %0) {
; GBI-O3-LABEL: sext16_i1:
; GBI-O3:       # %bb.0:
; GBI-O3-NEXT:    ld a, b
; GBI-O3-NEXT:    and $01
; GBI-O3-NEXT:    dec a
; GBI-O3-NEXT:    cpl
; GBI-O3-NEXT:    ld l, a
; GBI-O3-NEXT:    ld h, a
; GBI-O3-NEXT:    ret
  %res = sext i1 %0 to i16
  ret i16 %res
}

define fastcc i16 @sext16_i8(i8 %0) {
; GBI-O3-LABEL: sext16_i8:
; GBI-O3:       # %bb.0:
; GBI-O3-NEXT:    ld l, b
; GBI-O3-NEXT:    ld h, b
; GBI-O3-NEXT:    sra h
; GBI-O3-NEXT:    sra h
; GBI-O3-NEXT:    sra h
; GBI-O3-NEXT:    sra h
; GBI-O3-NEXT:    sra h
; GBI-O3-NEXT:    sra h
; GBI-O3-NEXT:    sra h
; GBI-O3-NEXT:    ret
  %res = sext i8 %0 to i16
  ret i16 %res
}

define fastcc i16 @zext16_i8(i8 %0) {
; GBI-O3-LABEL: zext16_i8:
; GBI-O3:       # %bb.0:
; GBI-O3-NEXT:    ld l, b
; GBI-O3-NEXT:    ld h, $00
; GBI-O3-NEXT:    ret
  %res = zext i8 %0 to i16
  ret i16 %res
}

declare void @llvm.trap() noreturn nounwind

define fastcc void @trap(i8 %0) noreturn {
; GBI-O3-LABEL: trap:
; GBI-O3:       # %bb.0:
; GBI-O3-NEXT:    trap
  call void @llvm.trap()
  unreachable
}

define i16 @test_memcpy() {
; GBI-O3-LABEL: test_memcpy:
; GBI-O3:       # %bb.0: # %entry
; GBI-O3-NEXT:    ld bc, $0000
; GBI-O3-NEXT:    ld de, $000a
; GBI-O3-NEXT:    ld h, b
; GBI-O3-NEXT:    ld l, c
; GBI-O3-NEXT:    call memcpy
; GBI-O3-NEXT:    ld hl, $0000
; GBI-O3-NEXT:    ret
entry:
  tail call void @llvm.memcpy.p0.p0.i16(ptr null, ptr null, i16 10, i1 false)
  ret i16 0
}

; Function Attrs: nocallback nofree nounwind willreturn memory(argmem: readwrite)
declare void @llvm.memcpy.p0.p0.i16(ptr noalias writeonly captures(none), ptr noalias readonly captures(none), i16, i1 immarg) #0


define void @inline_asm() {
; GBI-O3-LABEL: inline_asm:
; GBI-O3:       # %bb.0:
; GBI-O3-NEXT:    #APP
; GBI-O3-NEXT:    trap
; GBI-O3-NEXT:    #NO_APP
; GBI-O3-NEXT:    ret
  call void asm sideeffect "trap", ""()
  ret void
}


declare i8 @llvm.ctpop.i8(i8)
define i8 @ctpop(i8 %b) {
; GBI-O3-LABEL: ctpop:
; GBI-O3:       # %bb.0:
; GBI-O3-NEXT:    ld a, b
; GBI-O3-NEXT:    srl a
; GBI-O3-NEXT:    and $55
; GBI-O3-NEXT:    ld c, a
; GBI-O3-NEXT:    ld a, b
; GBI-O3-NEXT:    sub c
; GBI-O3-NEXT:    ld b, a
; GBI-O3-NEXT:    srl a
; GBI-O3-NEXT:    srl a
; GBI-O3-NEXT:    and $33
; GBI-O3-NEXT:    ld c, a
; GBI-O3-NEXT:    ld a, b
; GBI-O3-NEXT:    and $33
; GBI-O3-NEXT:    ld b, a
; GBI-O3-NEXT:    ld a, c
; GBI-O3-NEXT:    add b
; GBI-O3-NEXT:    ld b, a
; GBI-O3-NEXT:    swap a
; GBI-O3-NEXT:    and $0f
; GBI-O3-NEXT:    add b
; GBI-O3-NEXT:    and $0f
; GBI-O3-NEXT:    ret
  %1 = call i8 @llvm.ctpop.i8(i8 %b)
  ret i8 %1
}

declare i8 @llvm.cttz.i8(i8)
define i8 @cttz(i8 %b) {
; GBI-O3-LABEL: cttz:
; GBI-O3:       # %bb.0:
; GBI-O3-NEXT:    inc b
; GBI-O3-NEXT:    dec b
; GBI-O3-NEXT:    jr z, .LBB11_2
; GBI-O3-NEXT:  # %bb.1: # %cond.false
; GBI-O3-NEXT:    ld a, b
; GBI-O3-NEXT:    cpl
; GBI-O3-NEXT:    dec b
; GBI-O3-NEXT:    and b
; GBI-O3-NEXT:    ld b, a
; GBI-O3-NEXT:    srl a
; GBI-O3-NEXT:    and $55
; GBI-O3-NEXT:    ld c, a
; GBI-O3-NEXT:    ld a, b
; GBI-O3-NEXT:    sub c
; GBI-O3-NEXT:    ld b, a
; GBI-O3-NEXT:    srl a
; GBI-O3-NEXT:    srl a
; GBI-O3-NEXT:    and $33
; GBI-O3-NEXT:    ld c, a
; GBI-O3-NEXT:    ld a, b
; GBI-O3-NEXT:    and $33
; GBI-O3-NEXT:    ld b, a
; GBI-O3-NEXT:    ld a, c
; GBI-O3-NEXT:    add b
; GBI-O3-NEXT:    ld b, a
; GBI-O3-NEXT:    swap a
; GBI-O3-NEXT:    and $0f
; GBI-O3-NEXT:    add b
; GBI-O3-NEXT:    and $0f
; GBI-O3-NEXT:    ret
; GBI-O3-NEXT:  .LBB11_2:
; GBI-O3-NEXT:    ld a, $08
; GBI-O3-NEXT:    ret
  %1 = call i8 @llvm.cttz.i8(i8 %b)
  ret i8 %1
}

declare i8 @llvm.ctlz.i8(i8)
define i8 @ctlz(i8 %b) {
; GBI-O3-LABEL: ctlz:
; GBI-O3:       # %bb.0:
; GBI-O3-NEXT:    inc b
; GBI-O3-NEXT:    dec b
; GBI-O3-NEXT:    jr z, .LBB12_2
; GBI-O3-NEXT:  # %bb.1: # %cond.false
; GBI-O3-NEXT:    ld c, b
; GBI-O3-NEXT:    srl c
; GBI-O3-NEXT:    ld a, b
; GBI-O3-NEXT:    or c
; GBI-O3-NEXT:    ld b, a
; GBI-O3-NEXT:    srl b
; GBI-O3-NEXT:    srl b
; GBI-O3-NEXT:    or b
; GBI-O3-NEXT:    ld b, a
; GBI-O3-NEXT:    swap a
; GBI-O3-NEXT:    and $0f
; GBI-O3-NEXT:    ld c, a
; GBI-O3-NEXT:    ld a, b
; GBI-O3-NEXT:    or c
; GBI-O3-NEXT:    ld b, a
; GBI-O3-NEXT:    srl a
; GBI-O3-NEXT:    and $55
; GBI-O3-NEXT:    ld c, a
; GBI-O3-NEXT:    ld a, b
; GBI-O3-NEXT:    sub c
; GBI-O3-NEXT:    ld b, a
; GBI-O3-NEXT:    srl a
; GBI-O3-NEXT:    srl a
; GBI-O3-NEXT:    and $33
; GBI-O3-NEXT:    ld c, a
; GBI-O3-NEXT:    ld a, b
; GBI-O3-NEXT:    and $33
; GBI-O3-NEXT:    ld b, a
; GBI-O3-NEXT:    ld a, c
; GBI-O3-NEXT:    add b
; GBI-O3-NEXT:    ld b, a
; GBI-O3-NEXT:    swap a
; GBI-O3-NEXT:    and $0f
; GBI-O3-NEXT:    add b
; GBI-O3-NEXT:    and $0f
; GBI-O3-NEXT:    ld b, a
; GBI-O3-NEXT:    ld a, $08
; GBI-O3-NEXT:    sub b
; GBI-O3-NEXT:    ret
; GBI-O3-NEXT:  .LBB12_2:
; GBI-O3-NEXT:    ld a, $08
; GBI-O3-NEXT:    ret
  %1 = call i8 @llvm.ctlz.i8(i8 %b)
  ret i8 %1
}
