; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 3
; RUN: llc -mtriple=gb -verify-machineinstrs -O3 < %s \
; RUN:   | FileCheck %s -check-prefix=GBI-O3

define fastcc i32 @large_stack_i32_identity(i32 %0) {
; GBI-O3-LABEL: large_stack_i32_identity:
; GBI-O3:       # %bb.0: # %begin
; GBI-O3-NEXT:    ld a, c
; GBI-O3-NEXT:    ldi (hl), a
; GBI-O3-NEXT:    ld a, b
; GBI-O3-NEXT:    ldi (hl), a
; GBI-O3-NEXT:    ld a, e
; GBI-O3-NEXT:    ldi (hl), a
; GBI-O3-NEXT:    ld a, d
; GBI-O3-NEXT:    ld (hl), a
; GBI-O3-NEXT:    ret
begin:
  ret i32 %0
}
